# Pull official alpine based image
FROM arm64v8/alpine:3.17

# Install instruments
RUN apk update && apk upgrade && \
    apk add git && \
    apk add cmake && \
    apk add clang

WORKDIR /home/alpine

CMD ["/bin/sh"]



